### ISSUE TITLE
can't seem to install this on WSL Ubuntu.

### ISSUE THREAD

**Issue by jaykannan** [natemcmaster/dnvm#2]
I've tried to install this on WSL Ubuntu and I get this issue

`brew install dnvm
==> Installing dnvm from natemcmaster/dnvm
==> Installing dependencies for natemcmaster/dnvm/dnvm: patchelf, openssl, libyaml
==> Installing natemcmaster/dnvm/dnvm dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/00/00c02e6c700f4427da40a82e2a5d88427cfb28a79b3ac69f441d69d8377######################################################################## 100.0%
==> Pouring patchelf-0.9_1.x86_64_linux.bottle.tar.gz
�  /home/jay/.linuxbrew/Cellar/patchelf/0.9_1: 6 files, 1.2MB
==> Installing natemcmaster/dnvm/dnvm dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2p.tar.gz
######################################################################## 100.0%
==> perl ./Configure --prefix=/home/jay/.linuxbrew/Cellar/openssl/1.0.2p --openssldir=/home/jay/.linuxbrew/etc==> make depend
==> make
==> make test
==> make install MANDIR=/home/jay/.linuxbrew/Cellar/openssl/1.0.2p/share/man MANSUFFIX=ssl
==> Downloading https://curl.haxx.se/ca/cacert-2017-01-18.pem
######################################################################## 100.0%
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /home/jay/.linuxbrew/etc/openssl/certs

and run
  /home/jay/.linuxbrew/opt/openssl/bin/c_rehash
==> Summary
�  /home/jay/.linuxbrew/Cellar/openssl/1.0.2p: 1,792 files, 14.1MB, built in 16 minutes 37 seconds
==> Installing natemcmaster/dnvm/dnvm dependency: libyaml
==> Downloading https://linuxbrew.bintray.com/bottles/libyaml-0.2.1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/d3/d3fca10898eb53ec6d70a683a157cfb685cb238c46aa5dda65d21220cbc######################################################################## 100.0%
==> Pouring libyaml-0.2.1.x86_64_linux.bottle.tar.gz
�  /home/jay/.linuxbrew/Cellar/libyaml/0.2.1: 10 files, 1.2MB
==> Installing natemcmaster/dnvm/dnvm
==> Downloading https://dnvmtools.blob.core.windows.net/cli/0.2.0/dnvm.osx-x64.0.2.0.tar.gz
######################################################################## 100.0%
mv: '/home/jay/.linuxbrew/Cellar/dnvm/0.2.0/bin/dotnet' and '/home/jay/.linuxbrew/Cellar/dnvm/0.2.0/bin/dotnet' are the same file
Error: An exception occured within a child process:
  RuntimeError:`

**Comment by natemcmaster** [comment]
I didn't know brew was supported on WSL Ubuntu. This project does not yet support that platform. This is largely experimental. I've only made it work on my macbook. I'd be happy to take a PR which adds support for newer platforms.
